# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('word_type', models.CharField(max_length=10)),
                ('meaning', models.CharField(max_length=200)),
            ],
        ),
    ]
