# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20170803_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Diction',
        ),
    ]
